// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsCj_4I-ImbWBH7Xk0kZl50FYyAL7DSqw',
    appId: '1:396121178597:web:c61ed49a5a1da3ec0c6f0c',
    messagingSenderId: '396121178597',
    projectId: 'pill-box-d5fe4',
    authDomain: 'pill-box-d5fe4.firebaseapp.com',
    storageBucket: 'pill-box-d5fe4.firebasestorage.app',
    measurementId: 'G-ZZ9BSJXNXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQT2PY81z3ULrShVPMNa4KKDoHRi1p7P8',
    appId: '1:396121178597:android:76b5446880854c200c6f0c',
    messagingSenderId: '396121178597',
    projectId: 'pill-box-d5fe4',
    storageBucket: 'pill-box-d5fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1AVE6bv51_stijKGq7Wb9KAkK8_yGv8g',
    appId: '1:396121178597:ios:c8dbecdb457006b20c6f0c',
    messagingSenderId: '396121178597',
    projectId: 'pill-box-d5fe4',
    storageBucket: 'pill-box-d5fe4.firebasestorage.app',
    iosBundleId: 'com.example.pillBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1AVE6bv51_stijKGq7Wb9KAkK8_yGv8g',
    appId: '1:396121178597:ios:c8dbecdb457006b20c6f0c',
    messagingSenderId: '396121178597',
    projectId: 'pill-box-d5fe4',
    storageBucket: 'pill-box-d5fe4.firebasestorage.app',
    iosBundleId: 'com.example.pillBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsCj_4I-ImbWBH7Xk0kZl50FYyAL7DSqw',
    appId: '1:396121178597:web:a9f932911f24ce880c6f0c',
    messagingSenderId: '396121178597',
    projectId: 'pill-box-d5fe4',
    authDomain: 'pill-box-d5fe4.firebaseapp.com',
    storageBucket: 'pill-box-d5fe4.firebasestorage.app',
    measurementId: 'G-XWFGC2FP9B',
  );
}
